//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Application
{
    public int Id { get; set; }
    public string name { get; set; }
    public string genre { get; set; }
    public string developerUsername { get; set; }

    public virtual Developer Developer { get; set; }
}

public partial class Article
{
    public int Id { get; set; }
    public string title { get; set; }
    public string content { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string articleOwnerUsername { get; set; }
    public string articleAuthorUsername { get; set; }
}

public partial class aspnet_Applications
{
    public aspnet_Applications()
    {
        this.aspnet_Membership = new HashSet<aspnet_Membership>();
        this.aspnet_Paths = new HashSet<aspnet_Paths>();
        this.aspnet_Roles = new HashSet<aspnet_Roles>();
        this.aspnet_Users = new HashSet<aspnet_Users>();
    }

    public string ApplicationName { get; set; }
    public string LoweredApplicationName { get; set; }
    public System.Guid ApplicationId { get; set; }
    public string Description { get; set; }

    public virtual ICollection<aspnet_Membership> aspnet_Membership { get; set; }
    public virtual ICollection<aspnet_Paths> aspnet_Paths { get; set; }
    public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
    public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
}

public partial class aspnet_Membership
{
    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string Password { get; set; }
    public int PasswordFormat { get; set; }
    public string PasswordSalt { get; set; }
    public string MobilePIN { get; set; }
    public string Email { get; set; }
    public string LoweredEmail { get; set; }
    public string PasswordQuestion { get; set; }
    public string PasswordAnswer { get; set; }
    public bool IsApproved { get; set; }
    public bool IsLockedOut { get; set; }
    public System.DateTime CreateDate { get; set; }
    public System.DateTime LastLoginDate { get; set; }
    public System.DateTime LastPasswordChangedDate { get; set; }
    public System.DateTime LastLockoutDate { get; set; }
    public int FailedPasswordAttemptCount { get; set; }
    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    public int FailedPasswordAnswerAttemptCount { get; set; }
    public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
    public string Comment { get; set; }

    public virtual aspnet_Applications aspnet_Applications { get; set; }
    public virtual aspnet_Users aspnet_Users { get; set; }
}

public partial class aspnet_Paths
{
    public aspnet_Paths()
    {
        this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid PathId { get; set; }
    public string Path { get; set; }
    public string LoweredPath { get; set; }

    public virtual aspnet_Applications aspnet_Applications { get; set; }
    public virtual aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsers { get; set; }
    public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
}

public partial class aspnet_PersonalizationAllUsers
{
    public System.Guid PathId { get; set; }
    public byte[] PageSettings { get; set; }
    public System.DateTime LastUpdatedDate { get; set; }

    public virtual aspnet_Paths aspnet_Paths { get; set; }
}

public partial class aspnet_PersonalizationPerUser
{
    public System.Guid Id { get; set; }
    public Nullable<System.Guid> PathId { get; set; }
    public Nullable<System.Guid> UserId { get; set; }
    public byte[] PageSettings { get; set; }
    public System.DateTime LastUpdatedDate { get; set; }

    public virtual aspnet_Paths aspnet_Paths { get; set; }
    public virtual aspnet_Users aspnet_Users { get; set; }
}

public partial class aspnet_Profile
{
    public System.Guid UserId { get; set; }
    public string PropertyNames { get; set; }
    public string PropertyValuesString { get; set; }
    public byte[] PropertyValuesBinary { get; set; }
    public System.DateTime LastUpdatedDate { get; set; }

    public virtual aspnet_Users aspnet_Users { get; set; }
}

public partial class aspnet_Roles
{
    public aspnet_Roles()
    {
        this.aspnet_Users = new HashSet<aspnet_Users>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid RoleId { get; set; }
    public string RoleName { get; set; }
    public string LoweredRoleName { get; set; }
    public string Description { get; set; }

    public virtual aspnet_Applications aspnet_Applications { get; set; }
    public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
}

public partial class aspnet_SchemaVersions
{
    public string Feature { get; set; }
    public string CompatibleSchemaVersion { get; set; }
    public bool IsCurrentVersion { get; set; }
}

public partial class aspnet_Users
{
    public aspnet_Users()
    {
        this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
        this.aspnet_Roles = new HashSet<aspnet_Roles>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string UserName { get; set; }
    public string LoweredUserName { get; set; }
    public string MobileAlias { get; set; }
    public bool IsAnonymous { get; set; }
    public System.DateTime LastActivityDate { get; set; }

    public virtual aspnet_Applications aspnet_Applications { get; set; }
    public virtual aspnet_Membership aspnet_Membership { get; set; }
    public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
    public virtual aspnet_Profile aspnet_Profile { get; set; }
    public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
}

public partial class aspnet_WebEvent_Events
{
    public string EventId { get; set; }
    public System.DateTime EventTimeUtc { get; set; }
    public System.DateTime EventTime { get; set; }
    public string EventType { get; set; }
    public decimal EventSequence { get; set; }
    public decimal EventOccurrence { get; set; }
    public int EventCode { get; set; }
    public int EventDetailCode { get; set; }
    public string Message { get; set; }
    public string ApplicationPath { get; set; }
    public string ApplicationVirtualPath { get; set; }
    public string MachineName { get; set; }
    public string RequestUrl { get; set; }
    public string ExceptionType { get; set; }
    public string Details { get; set; }
}

public partial class AuthUser
{
    public AuthUser()
    {
        this.follows = new HashSet<follow>();
        this.follows1 = new HashSet<follow>();
        this.memberPhotos = new HashSet<memberPhoto>();
        this.memberSheetMusics = new HashSet<memberSheetMusic>();
        this.photoComments = new HashSet<photoComment>();
        this.sheetMusicComments = new HashSet<sheetMusicComment>();
        this.userLikeImgs = new HashSet<userLikeImg>();
        this.userLikeSms = new HashSet<userLikeSm>();
    }

    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> dob { get; set; }
    public string question { get; set; }
    public string answer { get; set; }

    public virtual ICollection<follow> follows { get; set; }
    public virtual ICollection<follow> follows1 { get; set; }
    public virtual ICollection<memberPhoto> memberPhotos { get; set; }
    public virtual ICollection<memberSheetMusic> memberSheetMusics { get; set; }
    public virtual ICollection<photoComment> photoComments { get; set; }
    public virtual ICollection<sheetMusicComment> sheetMusicComments { get; set; }
    public virtual ICollection<userLikeImg> userLikeImgs { get; set; }
    public virtual ICollection<userLikeSm> userLikeSms { get; set; }
}

public partial class Developer
{
    public Developer()
    {
        this.Applications = new HashSet<Application>();
    }

    public string username { get; set; }
    public string password { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string email { get; set; }

    public virtual ICollection<Application> Applications { get; set; }
}

public partial class follow
{
    public int followId { get; set; }
    public string username { get; set; }
    public string follower { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual AuthUser AuthUser1 { get; set; }
}

public partial class memberPhoto
{
    public memberPhoto()
    {
        this.photoComments = new HashSet<photoComment>();
        this.userLikeImgs = new HashSet<userLikeImg>();
    }

    public int Id { get; set; }
    public string imgurl { get; set; }
    public string ownername { get; set; }
    public System.DateTime createTime { get; set; }
    public string imgTitle { get; set; }
    public string imgDesc { get; set; }
    public int likes { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual ICollection<photoComment> photoComments { get; set; }
    public virtual ICollection<userLikeImg> userLikeImgs { get; set; }
}

public partial class memberSheetMusic
{
    public memberSheetMusic()
    {
        this.sheetMusicComments = new HashSet<sheetMusicComment>();
        this.userLikeSms = new HashSet<userLikeSm>();
    }

    public int Id { get; set; }
    public string smurl { get; set; }
    public string ownername { get; set; }
    public System.DateTime createTime { get; set; }
    public string smTitle { get; set; }
    public string smDesc { get; set; }
    public int likes { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual ICollection<sheetMusicComment> sheetMusicComments { get; set; }
    public virtual ICollection<userLikeSm> userLikeSms { get; set; }
}

public partial class photoComment
{
    public int Id { get; set; }
    public int pId { get; set; }
    public System.DateTime createTime { get; set; }
    public string username { get; set; }
    public string comment { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual memberPhoto memberPhoto { get; set; }
}

public partial class Post
{
    public int Id { get; set; }
    public string title { get; set; }
    public string content { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string ownerUsername { get; set; }
    public string authorUsername { get; set; }

    public virtual User User { get; set; }
    public virtual User User1 { get; set; }
}

public partial class sheetMusicComment
{
    public int Id { get; set; }
    public int smId { get; set; }
    public System.DateTime createTime { get; set; }
    public string username { get; set; }
    public string comment { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual memberSheetMusic memberSheetMusic { get; set; }
}

public partial class Sponsor
{
    public Sponsor()
    {
        this.Sponsoreds = new HashSet<Sponsored>();
    }

    public int Id { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string email { get; set; }
    public string username { get; set; }
    public string password { get; set; }

    public virtual ICollection<Sponsored> Sponsoreds { get; set; }
}

public partial class Sponsored
{
    public int Id { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string country { get; set; }
    public string continent { get; set; }
    public Nullable<int> sponsoredId { get; set; }

    public virtual Sponsor Sponsor { get; set; }
}

public partial class User
{
    public User()
    {
        this.Posts = new HashSet<Post>();
        this.Posts1 = new HashSet<Post>();
    }

    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public Nullable<System.DateTime> dob { get; set; }
    public Nullable<bool> sponsor { get; set; }
    public Nullable<bool> sponsored { get; set; }

    public virtual ICollection<Post> Posts { get; set; }
    public virtual ICollection<Post> Posts1 { get; set; }
}

public partial class User1
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }
}

public partial class UserActivation
{
    public int UserId { get; set; }
    public System.Guid ActivationCode { get; set; }
}

public partial class userLikeImg
{
    public int likeId { get; set; }
    public string username { get; set; }
    public int photoId { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual memberPhoto memberPhoto { get; set; }
}

public partial class userLikeSm
{
    public int likeId { get; set; }
    public string username { get; set; }
    public int smId { get; set; }

    public virtual AuthUser AuthUser { get; set; }
    public virtual memberSheetMusic memberSheetMusic { get; set; }
}
