//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class rheaxuEntities : DbContext
{
    public rheaxuEntities()
        : base("name=rheaxuEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Application> Applications { get; set; }
    public DbSet<Article> Articles { get; set; }
    public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
    public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
    public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
    public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
    public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
    public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
    public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
    public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
    public DbSet<aspnet_Users> aspnet_Users { get; set; }
    public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
    public DbSet<AuthUser> AuthUsers { get; set; }
    public DbSet<Developer> Developers { get; set; }
    public DbSet<follow> follows { get; set; }
    public DbSet<memberPhoto> memberPhotos { get; set; }
    public DbSet<memberSheetMusic> memberSheetMusics { get; set; }
    public DbSet<photoComment> photoComments { get; set; }
    public DbSet<Post> Posts { get; set; }
    public DbSet<sheetMusicComment> sheetMusicComments { get; set; }
    public DbSet<Sponsor> Sponsors { get; set; }
    public DbSet<Sponsored> Sponsoreds { get; set; }
    public DbSet<User> Users { get; set; }
    public DbSet<UserActivation> UserActivations { get; set; }
    public DbSet<userLikeImg> userLikeImgs { get; set; }
    public DbSet<userLikeSm> userLikeSms { get; set; }
    public DbSet<User1> Users1 { get; set; }
}
